# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-18 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('comment_count', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
