# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-15 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AddField(
            model_name='entry',
            name='modified',
            field=models.DateTimeField(null=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='post date'),
        ),
    ]
